name: ESlint

on:
  push:
      branches:
          - dev
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install yarn dependencies
      run: cd app && yarn install --frozen-lockfile
    - name: Run linter
      run: cd app && yarn lint
    - name: Run type checking
      run: cd app && yarn type-check
